### ISSUE TITLE
16000+ files?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [hsbalar/Preserver#1]
Are you for real?!

**Comment by hsbalar** [comment]
What you mean by ?

**Comment by Unrepentant-Atheist** [comment]
I mean a simple tool like that has over 16000 files. WTF?

**Comment by hsbalar** [comment]
Actually i m experimenting server sync &  this is all about ..yes there many modules which are i m not using yet. The devDependencies is not needed any more once you build app with webpack so you can remove that modules after build. but you can mold it as you want.

**Comment by hsbalar** [comment]
Just make it very light.
