### ISSUE TITLE
not rebuild in electron

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [hsbalar/Preserver#6]
I'm trying to reuse your code for another project but it does not compile

Your project is very good. congratulations

**Comment by hsbalar** [comment]
Updating with latest dependency. Will sort out your issue.

**Comment by luizcarlospedrosogomes** [comment]
thanks for the answer. how do I do that?

**Comment by luizcarlospedrosogomes** [comment]
after command
$ npm install -g npm-check-updates
$ npm-check-updates -u
$ npm install 

Displayed the following error and did not compliment

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).

thanks for the answer. I appreciate your work

**Comment by hsbalar** [comment]
@luizcarlospedrosogomes Preserver is updated. Try` npm run build` then `npm start`

**Comment by luizcarlospedrosogomes** [comment]
@hsbalar  tank you!!!!!!!!!!!! very good!!!!!!!!!!!!!!!!!!!
